dev_manager_reply:
    description: >
      1. DEVI UTILIZZARE l'output deL TOOL read_discord_messages come input per RISPONDERE
      1. Leggi ESCLUSIVAMENTE i messaggi ricevuti dal tool read_discord_messages, che devi trattare come una chat in tempo reale.
      3. GENERA UNA RISPOSTA CORENTE COME SE FACESSI PARTE DELLA CHAT
      2. NON inventare, simulare o ricostruire conversazioni, dialoghi o messaggi che non siano
         esplicitamente presenti nei dati restituiti dal tool.
      3. NON creare esempi di conversazione, ruoli o scambi fittizi.
      4. Usa SOLO i messaggi realmente letti come input.
      5. Genera UNA SOLA risposta coerente con quei messaggi.
      6. Posta SOLO il messaggio finale su Discord usando send_discord_webhook,
         passando come primo parametro "Backend Developer" e come secondo parametro il testo del messaggio.

    expected_output: >
      un messaggio coerente con i messaggi/o letti/o attraverso il tool read_discord_messages.
    agent: dev_manager


dev_junior_reply:
    description: >
      1. Leggi ESCLUSIVAMENTE i messaggi presenti nella chat Discord usando il tool read_discord_messages, che devi trattare come una chat in tempo reale.
      2. NON inventare, simulare o ricostruire conversazioni, dialoghi o messaggi che non siano
         esplicitamente presenti nei dati restituiti dal tool.
      3. NON creare esempi di conversazione, ruoli o scambi fittizi.
      4. Usa SOLO i messaggi realmente letti come input.
      5. Genera UNA SOLA risposta coerente con quei messaggi.
      6. Posta SOLO il messaggio finale su Discord usando send_discord_webhook,
         passando come primo parametro "Backend Developer" e come secondo parametro il testo del messaggio.
    expected_output: >
      un messaggio coerente con i messaggi/o letti/o attraverso il tool read_discord_messages.
    agent: dev_junior